### ISSUE TITLE
scater_max

### ISSUE THREAD

**Issue by bolinpu** [rusty1s/pytorch_geometric#102]
I encountered a very strange "illegle memory access" bug when I try to use the scater_max or softmax() which is based on the scater_max. I am sure that, the "source", "index", "dim_size" is right. Do anybody else meet the same prob?

  File "/home/bl1/anaconda3/lib/python3.6/site-packages/torch_geometric/utils/softmax.py", line 21, in softmax
    out = src - scatter_max(src, index, dim=0, dim_size=num_nodes)[0][index]
RuntimeError: CUDA error: an illegal memory access was encountered

**Comment by rusty1s** [comment]
Are you are sure that all your inputs are on the same device?

**Comment by bolinpu** [comment]
> Are you are sure that all your inputs are on the same device?
Actually, I only use one GPU. The interest is that this error is related to my training iteration. I really can't understand it.

**Comment by bolinpu** [comment]
In addition, the scatter_mean is OK

**Comment by rusty1s** [comment]
Can you try `scatter_max` in a REPL or run the test suite of `torch-scatter`?

**Comment by bolinpu** [comment]
I comment the "out = src - scatter_max(src, index, dim=0, dim_size=num_nodes)[0][index]". It works fine now. There must be some werid thing related to scatter_max.  But I can't  figure it out now

**Comment by VoVAllen** [comment]
Do you have multiple gpus? Which one do you use?

**Comment by bolinpu** [comment]
@VoVAllen Yes, I have multiple gpus, but I only use the second one. The werid thing is that scatter_mean is fine

**Comment by rusty1s** [comment]
I have an open issue regarding multi gpu support and PyTorch extensions: https://github.com/pytorch/extension-cpp/issues/18
I‘m gonna keep following this up.

**Comment by VoVAllen** [comment]
You can use `torch.cuda.set_device(1)` to change the default context manager.

**Comment by bolinpu** [comment]
@VoVAllen I used the command of device = torch.device('cuda:1'). if they are the same?

**Comment by VoVAllen** [comment]
No they are not. Custom cuda kernel will get CUDAStream from default device, not the device which tensor is on. You have to change the default device to let kernel get correct CUDAStream

**Comment by rusty1s** [comment]
Fixed now in `torch-scatter-1.1.2` :)
