### ISSUE TITLE
Example code: an illegal memory access was encountered

### ISSUE THREAD

**Issue by yanghtr** [rusty1s/pytorch_geometric#1054]
## To Reproduce

1. Follows the instructions to install pytorch_geometric
2. download `pytorch_geometric/examples/pointnet2_classification.py`
3. run `CUDA_VISIBLE_DEVICES=0  python pointnet2_classification.py`

## Expected behavior

The network should be trained successfully. However, it shows the error:
```
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCReduceAll.cuh line=327 error=700 : an illegal memory access was encountered
Traceback (most recent call last):
  File "pointnet2_classification.py", line 115, in <module>
    train(epoch)
  File "pointnet2_classification.py", line 82, in train
    loss = F.nll_loss(model(data), data.y)
  File "/home/***/miniconda2/envs/pytorch14/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "pointnet2_classification.py", line 63, in forward
    sa1_out = self.sa1_module(*sa0_out)
  File "/home/***/miniconda2/envs/pytorch14/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "pointnet2_classification.py", line 22, in forward
    max_num_neighbors=64)
  File "/home/***/miniconda2/envs/pytorch14/lib/python3.6/site-packages/torch_geometric/nn/pool/__init__.py", line 159, in radius
    return torch_cluster.radius(x, y, r, batch_x, batch_y, max_num_neighbors)
  File "/home/***/miniconda2/envs/pytorch14/lib/python3.6/site-packages/torch_cluster/radius.py", line 54, in radius
    batch_size = int(batch_x.max()) + 1
RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /pytorch/aten/src/THC/THCReduceAll.cuh:327
```

I also try `CUDA_LAUNCH_BLOCKING=1` to track where the error occur. The error message is:
```
Traceback (most recent call last):
  File "pointnet2_classification.py", line 115, in <module>
    train(epoch)
  File "pointnet2_classification.py", line 82, in train
    loss = F.nll_loss(model(data), data.y)
  File "/home/***/miniconda2/envs/pytorch14/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "pointnet2_classification.py", line 63, in forward
    sa1_out = self.sa1_module(*sa0_out)
  File "/home/***/miniconda2/envs/pytorch14/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "pointnet2_classification.py", line 21, in forward
    row, col = radius(pos, pos[idx], self.r, batch, batch[idx],
RuntimeError: CUDA error: an illegal memory access was encountered
```

## Environment

* OS: Ubuntu 16.04
* Python version: 3.6
* PyTorch version: 1.4.0
* CUDA/cuDNN version: CUDA 10.1, cudnn 7.5
* GCC version: 5.4.0
* Any other relevant information: I use miniconda, and create an environment of python3.6

**Comment by rusty1s** [comment]
Seems to be a problem with the new `fps` function of `torch-cluster`. I am working on it.

**Comment by rusty1s** [comment]
I fixed this issue in `torch-cluster` master and am now working on a new release.

**Comment by yanghtr** [comment]
@rusty1s .Hi, I still have the bug. I update the `torch-cluster` and the code could run several epochs. However, after several epochs, it runs into the same bug:
```
Epoch: 001, Test: 0.5099
Epoch: 002, Test: 0.7026
Epoch: 003, Test: 0.7313
Epoch: 004, Test: 0.7181
Epoch: 005, Test: 0.8007
Epoch: 006, Test: 0.8128
Epoch: 007, Test: 0.8436
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCReduceAll.cuh line=327 error=700 : an illegal memory access was encountered
Traceback (most recent call last):
  File "pointnet2_classification.py", line 115, in <module>
    train(epoch)
  File "pointnet2_classification.py", line 82, in train
    loss = F.nll_loss(model(data), data.y)
  File "/home/***/Software/miniconda2/envs/pytorch14/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "pointnet2_classification.py", line 63, in forward
    sa1_out = self.sa1_module(*sa0_out)
  File "/home/***/Software/miniconda2/envs/pytorch14/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "pointnet2_classification.py", line 22, in forward
    max_num_neighbors=64)
  File "/home/***/Software/miniconda2/envs/pytorch14/lib/python3.6/site-packages/torch_geometric/nn/pool/__init__.py", line 159, in radius
    return torch_cluster.radius(x, y, r, batch_x, batch_y, max_num_neighbors)
  File "/home/***/Software/miniconda2/envs/pytorch14/lib/python3.6/site-packages/torch_cluster/radius.py", line 54, in radius
    batch_size = int(batch_x.max()) + 1
RuntimeError: cuda runtime error (700) : an illegal memory access was encountered at /pytorch/aten/src/THC/THCReduceAll.cuh:327
```

Could you help with this?

**Comment by rusty1s** [comment]
Mh, there seems to be still a bug going on. Let me look into it once more.

**Comment by yanghtr** [comment]
Add `__syncthreads();` before [this line](https://github.com/rusty1s/pytorch_cluster/blob/9c33077e0bcc0da42dc66e62a34a5e88a921b1c3/csrc/cuda/fps_cuda.cu#L28) seems to work.

**Comment by rusty1s** [comment]
Yes, that's it! Thank you! I will fix it.

**Comment by Bawaw** [comment]
Has the binary been released yet?

**Comment by rusty1s** [comment]
Not yet, will work on it.

**Comment by Pixie412** [comment]
Hi,
I am using torch-cluster 1.5.2 version. I also face this problem occasionally when I use torch_cluster.fps. How can I solve this problem?

**Comment by rusty1s** [comment]
Can you upgrade `torch-cluster` to see if this resolves your issues?

**Comment by Pixie412** [comment]
> Can you upgrade `torch-cluster` to see if this resolves your issues?

oh yes, looks the problem is solved when I upgrade it into 1.5.4.
