### ISSUE TITLE
GPU memory usage grows continually over time

### ISSUE THREAD

**Issue by jaredsagendorf** [rusty1s/pytorch_geometric#1595]
## ❓ Questions & Help

Hello, I've had some issues with my GPUs running out of memory. I did some profiling of the GPU memory usage in my code using [this](https://github.com/Stonesjtu/pytorch_memlab) tool, and found that the memory consumption increases continually until eventually the GPU goes OOM.

I thought it was my code's fault, but I profiled some of the examples here in this repo and found the same behaviour. For example, here is a profile of the pointnet2_segmentation.py example:

![mem1](https://user-images.githubusercontent.com/16827826/91892715-ffffaa80-ec47-11ea-93eb-a31dcb64f068.png)

Note that the memory usage was queried before and after each iteration over the training data during training. You can see that memory just goes up and up after each epoch, and if I continued this for enough epochs the GPU will eventually go OOM.

Is this expected behaviour? If so, why, and is there anything I can do to release memory during training?

**Comment by jaredsagendorf** [comment]
As a bit of extra info:

What happens is that for each batch, a new set of tensors is allocated in the GPU. Rather than re-using these tensors on subsequence epochs, these tensors are just left behind in memory and never garbage collected, until eventually you have thousands of them lying around and no memory left.

**Comment by jaredsagendorf** [comment]
Here is another plot, querying the memory usage before and after the gradients are computed for each batch. Again, something is left behind the the total memory usage climbs upwards.

![mem_usage](https://user-images.githubusercontent.com/16827826/91916894-31da3680-ec73-11ea-8de5-625a8e743007.png)

And here is some bare minimum code to generate the above plot. All you need to do is install pytorch_memlab. I hope some other people can confirm this result (using pytorch 1.6, CUDA 10.1 and torch_geometric 1.6.1)

`# GPU memory stuff
from pytorch_memlab import MemReporter
import sys
from io import StringIO
capture = StringIO()
sys.stdout = capture
####################################################################################################

import os.path as osp

import torch
import torch.nn.functional as F
from torch_geometric.datasets import ShapeNet
import torch_geometric.transforms as T
from torch_geometric.data import DataLoader
from torch_geometric.nn import knn_interpolate
from pointnet2_classification import SAModule, GlobalSAModule, MLP

class FPModule(torch.nn.Module):
    def __init__(self, k, nn):
        super(FPModule, self).__init__()
        self.k = k
        self.nn = nn

    def forward(self, x, pos, batch, x_skip, pos_skip, batch_skip):
        x = knn_interpolate(x, pos, pos_skip, batch, batch_skip, k=self.k)
        if x_skip is not None:
            x = torch.cat([x, x_skip], dim=1)
        x = self.nn(x)
        return x, pos_skip, batch_skip


class Net(torch.nn.Module):
    def __init__(self, num_classes):
        super(Net, self).__init__()
        self.sa1_module = SAModule(0.2, 0.2, MLP([3 + 3, 64, 64, 128]))
        self.sa2_module = SAModule(0.25, 0.4, MLP([128 + 3, 128, 128, 256]))
        self.sa3_module = GlobalSAModule(MLP([256 + 3, 256, 512, 1024]))

        self.fp3_module = FPModule(1, MLP([1024 + 256, 256, 256]))
        self.fp2_module = FPModule(3, MLP([256 + 128, 256, 128]))
        self.fp1_module = FPModule(3, MLP([128 + 3, 128, 128, 128]))

        self.lin1 = torch.nn.Linear(128, 128)
        self.lin2 = torch.nn.Linear(128, 128)
        self.lin3 = torch.nn.Linear(128, num_classes)

    def forward(self, data):
        sa0_out = (data.x, data.pos, data.batch)
        sa1_out = self.sa1_module(*sa0_out)
        sa2_out = self.sa2_module(*sa1_out)
        sa3_out = self.sa3_module(*sa2_out)

        fp3_out = self.fp3_module(*sa3_out, *sa2_out)
        fp2_out = self.fp2_module(*fp3_out, *sa1_out)
        x, _, _ = self.fp1_module(*fp2_out, *sa0_out)

        x = F.relu(self.lin1(x))
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.lin2(x)
        x = F.dropout(x, p=0.5, training=self.training)
        x = self.lin3(x)
        return F.log_softmax(x, dim=-1)

def train():
    model.train()
    for i, data in enumerate(train_loader):
        data = data.to(device)
        optimizer.zero_grad()
        out = model(data)
        
        # report memory usage before gradients
        reporter.report()
        
        loss = F.nll_loss(out, data.y)
        loss.backward()
        optimizer.step()

        # report memory usage after gradients
        reporter.report()

# Load Dataset
category = 'Airplane'  # Pass in `None` to train on all categories.
path = osp.join(osp.dirname(osp.realpath(__file__)), '..', 'data', 'ShapeNet')
transform = T.Compose([
    T.RandomTranslate(0.01),
    T.RandomRotate(15, axis=0),
    T.RandomRotate(15, axis=1),
    T.RandomRotate(15, axis=2)
])
pre_transform = T.NormalizeScale()
train_dataset = ShapeNet(path, category, split='trainval', transform=transform,
                         pre_transform=pre_transform)
train_loader = DataLoader(train_dataset, batch_size=12, shuffle=True,
                          num_workers=6)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = Net(train_dataset.num_classes).to(device)
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)

# Check GPU memory before training
reporter = MemReporter(model)
reporter.report()

# Do some training
for epoch in range(1, 2):
    train()

# Plot memory usage
import re
from matplotlib import pyplot as plt
stdout = capture.getvalue().split('\n')

# read the text generated by MemReporter to scrape the GPU memory values
tot_mem = []
for line in stdout:
    if re.search("The allocated memory on cuda:0", line):
        line = line.split()
        mem = float(line[-1][:-1])
        unit = line[-1][-1]
        
        if(unit == 'K'):
            # convert from KB to GB
            scale = 1e6
        if(unit == 'M'):
            # convert from MB to GB
            scale = 1e3
        else:
            scale = 1
        tot_mem.append(mem/scale)

# plot
plt.plot(tot_mem[1:])
plt.xlabel("iteration")
plt.ylabel("Total GPU Memory Usage (GB)")
plt.xlim(0, 100)
plt.savefig("mem_usage.png")`

**Comment by rusty1s** [comment]
Thanks for this interesting issue. I checked the code above and it seems like the memory issues reported by `pytorch_memlab` stems from the `data = data.to(device)` calls. IMO, I would expect that this data is freed automatically when it is no longer referenced. However, the following code also reports a continuous memory increase:
```python
reporter = MemReporter()
for _ in range(1, 2000):
    x = torch.randn(100000, 128).cuda()
    reporter.report()
```
That is weird...

**Comment by rusty1s** [comment]
After checking with the PyTorch team, it seems like this issue is caused by `memlab` itself, which still holds references to all the data objects created. Therefore, those objects are never freed. I'm closing this for now, since this is not a PyG issue.

**Comment by jaredsagendorf** [comment]
Thanks for your response! It's a depressing time when your memory debugger causes it's own memory leaks :(

I switched to the native GPU memory tools under `torch.cuda` - I still have some behaviour I don't understand, so I may open a new issue if I can't figure it out.

Sorry for any confusion

**Comment by rusty1s** [comment]
Sounds good. Please let me know if you encounter any other issues.

**Comment by Stonesjtu** [comment]
@rusty1s @jaredsagendorf  it's caused by the memory leak from `pytorch_memlab`, I just fixed it recently in https://github.com/Stonesjtu/pytorch_memlab/issues/17. 
You can get the correct memory information by upgrading the package from pypi.

Sorry for the misleading information.
