### ISSUE TITLE
CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Zerg-Overmind** [rusty1s/pytorch_geometric#1639]
## ❓ Questions & Help

![image](https://user-images.githubusercontent.com/35461133/93200509-6b866380-f782-11ea-905e-4e26e5219291.png)
I am trying to update the node embedding by using splineCNN, but there is a weird error: 
All is well during one epoch (I get the loss=2.373), but there occurs an error (CUDA error: an illegal memory access was encountered) at the second epoch immediately. I am sure that the input of splineCNN in the second epoch is the same as the first (data or features are all sampled from the same dataset). If there is something wrong with my code, it would early stop but it still finished a whole epoch. Why? 

--------------------------------------------------------------------------------------------------------------------------------------------
After moving the data into cpu to calculate "scatter_max", I encounter another error:
![image](https://user-images.githubusercontent.com/35461133/93282009-f78aa080-f7ff-11ea-8d02-41074df33878.png)

**Comment by rusty1s** [comment]
That is indeed weird, but this error usually occurs when `edge_index` has values smaller or equal/greater than the size of your node feature matrix. In general, you will only notice this error for the first/last example in a batch, which might explain the fact that this error only occurs in the second epoch. Can you please check that?

**Comment by Zerg-Overmind** [comment]
> That is indeed weird, but this error usually occurs when `edge_index` has values smaller or equal/greater than the size of your node feature matrix. In general, you will only notice this error for the first/last example in a batch, which might explain the fact that this error only occurs in the second epoch. Can you please check that?

Thanks for your reply! After I change the kernel size from 5 to 3, the error disappeared! And why will I only notice this error for the first/last example in a batch? I think there is no difference between the batch 1 and 2 (In a statistical sense), but why it occurs in different batch ? Besides, I will check the edge_index as suggested anyway :).

**Comment by rusty1s** [comment]
Because out of index errors can only appear for the first and last example in a batch.

**Comment by Zerg-Overmind** [comment]
> Because out of index errors can only appear for the first and last example in a batch.

Oh! Now I understand after checking the code, thanks again.

**Comment by Zerg-Overmind** [comment]
> That is indeed weird, but this error usually occurs when `edge_index` has values smaller or equal/greater than the size of your node feature matrix. In general, you will only notice this error for the first/last example in a batch, which might explain the fact that this error only occurs in the second epoch. Can you please check that?
 BTW, when "edge_index has values smaller or equal/greater than the size of your node feature matrix" , what should I do? Change the edge_index value??

**Comment by Zerg-Overmind** [comment]
> Because out of index errors can only appear for the first and last example in a batch.

BTW, when "edge_index has values smaller or equal/greater than the size of your node feature matrix" , what should I do? Change the edge_index value??

**Comment by rusty1s** [comment]
In general, that means that you have no features for nodes that exist in your graph, so you may to add those features to `x`.

**Comment by Zerg-Overmind** [comment]
> In general, that means that you have no features for nodes that exist in your graph, so you may to add those features to `x`.

Oh！I check the dataloader, there is an empty list of input points being sampled into my model and led to this error. Thank you for your kind reply, now I fix it.
