### ISSUE TITLE
libcudart.so.11.0 Error

### ISSUE THREAD

**Issue by sunnyyhyh** [rusty1s/pytorch_geometric#1902]
When I try `import torch_geometric.transforms`  
there would be an error:  
`OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory`
The complete error message is below:  
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/root/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/root/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/root/anaconda3/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/root/anaconda3/lib/python3.7/site-packages/torch_geometric/data/data.py", line 8, in <module>
    from torch_sparse import coalesce, SparseTensor
  File "/root/anaconda3/lib/python3.7/site-packages/torch_sparse/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/root/anaconda3/lib/python3.7/site-packages/torch/_ops.py", line 105, in load_library
    ctypes.CDLL(path)
  File "/root/anaconda3/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory
`  
my CUDA version:
`torch.version.cuda
'10.1'`

`nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
`

thank you~

**Comment by rusty1s** [comment]
Looks like you installed `torch-sparse` with CUDA 11.0 support. Can you try:
```
pip uninstall torch-sparse
pip uninstall torch-sparse
pip install --upgrade --no-cache-dir torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
```

**Comment by sunnyyhyh** [comment]
I try  
`pip uninstall torch-sparse  
pip install --upgrade --no-cache-dir torch-sparse -f https://pytorch-geometric.com/whl/torch-1.7.0+cu101.html
`
but not work, and try  
`
pip (un)install torch-scatter
pip (un)install torch-sparse
pip (un)install torch-cluster
pip (un)install torch-spline-conv
pip (un)install torch-geometric
`
now, the error is` Undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs`, and I will try [this](https://github.com/rusty1s/pytorch_geometric/issues/1080)

**Comment by rusty1s** [comment]
So the first command yields the same error as reported above? That is really weird, since this one shouldn't look for CUDA 11 libs.

**Comment by sunnyyhyh** [comment]
now, it's work...  
I dont know what happend, but I uninstall pytorch1.7, torch-geometric(include torch-scatter、torch-sparse..) and install them again, the error disappeared   
thanks for your help ~  
：）

**Comment by FantasyJXF** [comment]
> now, it's work... I dont know what happend, but I uninstall pytorch1.7, torch-geometric(include torch-scatter、torch-sparse..) and install them again, the error disappeared thanks for your help ~ ：）

I met the same problem today, the question might be the cuda version of ` torch-scatter、torch-sparse..` does not match the pytorch cuda version.

For example, I use pytorch_1.8.1+cu101, and I install `torch_scatter、torch_sparse..` with `pip install torch-scatter  torch-sparse  torch_geometric -f https://pytorch-geometric.com/whl/torch-1.8.1+cu101.html`.
**Here is the problem,** I got `torch-scatter==2.0.9` installed, but actually the latest verion of torch-scatter for torch-1.8.1+cu101 is [2.0.8](https://data.pyg.org/whl/torch-1.8.1%2Bcu101.html) 

So the solution is **install** `torch_geometric` and `torch_scatter、torch_sparse..`  **separately**. 
```
pip install torch_scatter torch_sparse -f https://data.pyg.org/whl/torch-1.8.1+cu101.html
pip install torch-geometric
```

**Comment by codebyte-ux** [comment]
OSError: libcudart.so.11.0: cannot open shared object file: No such file or directory  (getting this error while importing torch_geometric

**Comment by rusty1s** [comment]
Can you share some more information on how you installed PyG? Keep in mind that your CUDA versions need to match. In addition, upgrading to PyG 2.3 should resolve this issue as well.

**Comment by mainguyenanhvu** [comment]
I found the solution [here](https://stackoverflow.com/a/78340193/10987905).
