### ISSUE TITLE
Cuda issue with PyG 1.7.0

### ISSUE THREAD

**Issue by adhikarirsr** [rusty1s/pytorch_geometric#2490]
In the training phase I am getting this:
`RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling cublasCreate(handle)`

This what I have:

```
>>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.7.1908 (Core) (x86_64)
GCC version: (GCC) 6.2.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: Quadro RTX 8000
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.16.5
[pip3] torch==1.8.0
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==1.7.0
[pip3] torch-scatter==2.0.6
[pip3] torch-sparse==0.6.9
[pip3] torch-spline-conv==1.2.1
[pip3] torchvision==0.9.0
[conda] Could not collect

```
However `nvidia-smi` shows:
`| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |`

Also I have loaded cuda/10.2 becuase I installed troch-geometric 1.7.0-10.2:
`>>module list`

```
Currently Loaded Modules:
  1) gcc/6.2.0   2) openblas/0.2.19   3) python/3.7.4 (E)   4) cuda/10.2
```

**Comment by rusty1s** [comment]
When does that error occur exactly? Do our examples like `examples/gcn.py` work for you?

**Comment by adhikarirsr** [comment]
It occurs in the training phase. I tried running `gcn.py` and I got:

```
Traceback (most recent call last):
  File "testgcn.py", line 75, in <module>
    train()
  File "testgcn.py", line 58, in train
    F.nll_loss(model()[data.train_mask], data.y[data.train_mask]).backward()
  File "/home/s5/jupy37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "testgcn.py", line 41, in forward
    x = F.relu(self.conv1(x, edge_index, edge_weight))
  File "/home/s5/jupy37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/s5/jupy37/lib/python3.7/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 179, in forward
    x = x @ self.weight
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasCreate(handle)`
```

The same code runs fine in the following setup:

```
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: CentOS Linux release 7.7.1908 (Core)
GCC version: (GCC) 6.2.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: Quadro RTX 8000
Nvidia driver version: 460.32.03
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.5
[pip3] torch==1.6.0
[pip3] torch-cluster==1.5.9
[pip3] torch-geometric==1.7.0
[pip3] torch-scatter==2.0.6
[pip3] torch-sparse==0.6.9
[pip3] torch-spline-conv==1.2.1
[pip3] torchvision==0.7.0
[conda] Could not collect
```

**Comment by rusty1s** [comment]
Mh, I'm not sure to be honest. This error seems to come from PyTorch directly, see https://discuss.pytorch.org/t/cuda-error-cublas-status-internal-error-when-calling-cublascreate-handle/114341/10. Does the same error occur when replacing `GCNConv` with a simple `torch.nn.Linear` layer?

**Comment by adhikarirsr** [comment]
I remember going through that post. I think I tired their suggestions. I will give it a try again this weekend.

**Comment by rusty1s** [comment]
Does the same code work when replacing `GCNConv` with `torch.nn.Linear`?

**Comment by adhikarirsr** [comment]
Hi @rusty1s, 

The problem is solved now. There was some issue with ~/.local where jupyter stored some files. Deleting that folder and setting up the environment from scratch helped.

Thanks.

**Comment by rusty1s** [comment]
Awesome :)
