### ISSUE TITLE
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.

### ISSUE THREAD

**Issue by TrentHawkins** [rusty1s/pytorch_geometric#2651]
## 📚 Installation

I perform the installation from source per [instructions](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html)

## Environment

* OS: Manjaro Linux (kernel: Linux 5.12.2-1-MANJARO, arhitecture: x86-64)
* Python version: 3.9.5
* PyTorch version: 1.8.1-5
* CUDA/cuDNN version: 11.3 (Cuda compilation tools, release 11.3, V11.3.58, Build cuda_11.3.r11.3/compiler.29745058_0)
* GCC version: 10.2.0
* How did you try to install PyTorch Geometric and its extensions (wheel, source): I first tried 1.8.0+cu111 PyG wheels, since I have built PyTorch on cuda 11.3 (via official archlinux package). But seeing this error, I also tried to install from source after seeing this error. There is also an Arch User Repository (AUR) package for PyG, which however fails on several of the tests by that same error.
* Any other relevant information: `torch.version.cuda` returns `11.3`.

## Checklist

- [x] I followed the [installation guide](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html).
- [x] I cannot find my error message in the [FAQ](https://pytorch-geometric.readthedocs.io/en/latest/notes/installation.html#id1).
- [ ] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [x] I do have multiple CUDA versions on my machine.

## Additional context

Regarding the CUDA checkpoint, I haven't compiled explicitly any CUDA code before, however PyTorch works out of the box, whether installed from the arch official repos or from the pytorch wheels, I have tried both. The simplest snippet reproducing the error is the following, where so long as only `torch` is imported, everything is fine with a tensor on GPU, but as soon as `torch_geometric` is imported, `torch` on GPU fails.

plain torch:
```python
import torch
torch.tensor([0,1],device="cuda")
```
output:
```
tensor([0, 1], device='cuda:0')
```
against torch+geometric:
```python
import torch
import torch_geometric
torch.tensor([0,1],device="cuda")
```
output:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
```

Please advise.

**Comment by rusty1s** [comment]
I think this is related to the usage of CUDA 11.3 for loading the external package. What does
```python
from torch.utils.cpp_extension import CUDA_HOME
print(CUDA_HOME)
```
output?

**Comment by TrentHawkins** [comment]
Hi, thanks for the reply.
The output is `/opt/cuda`.

Also my `$PATH` contains `/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_systems/bin`.

**Comment by rusty1s** [comment]
I see. I do not maintain the Arch package though.

Your best bet is to install the extensions from source using CUDA 11.3, as we do not provide binaries for this CUDA version yet.

**Comment by TrentHawkins** [comment]
ΟΚ, AUR packages are always building from source anyways, and in this I see that it simply runs setup.py, with tests and sets the appropriate paths. I'll explore deeper into building the dependent packages (scatter, sparse, cluster, spline-conv) and geometric itself step by step instead. I'll leave this open for now just in case I'll need to post my steps for a successful build. Thank you.

**Comment by TrentHawkins** [comment]
In relevance to this issue, it seems that the fault was the delayed nvidia driver update for Arch, so driver CUDA was still 11.2 while CUDA compiler was 11.3. Problem is solved, and issue closed (and non-related to this library). Thanks again @rusty1s!
