### ISSUE TITLE
CUDA errors with related packages

### ISSUE THREAD

**Issue by zhiqiangzhongddu** [rusty1s/pytorch_geometric#469]
## Environment

* OS: Ubuntu (HPC server of university)
* Python version: (3.7.3)
* PyTorch version: 1.1.0
* CUDA/cuDNN version: 9.0.176
* GCC version: 7.3.0
* How did you try to install PyTorch Geometric and its extensions (pip, source): tried pip and source
* Any other relevant information:

## Checklist

- [x] I followed the installation guide.
- [x] I cannot find my error message in the FAQ.
- [x] I set up CUDA correctly and can compile CUDA code via `nvcc`.
- [x] I have cloned the repository and tried a manual installation from source.
- [x] I do have multiple CUDA versions on my machine.
- [x] I checked if the official extension example runs on my machine.
- [ ] The offical extension example runs on my machine.

## Additional context

Here are information of my NVCC and GCC:
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:01_CDT_2018
Cuda compilation tools, release 10.0, V10.0.130

gcc (GCC) 5.2.0
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

The problem is that I got no error while I test in the folder of pytorch_scatter (python setup.py test), but I got an error of "ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'" when I test the installation in the pytorch_sparse folder. 

I suppose it should be the problem of CUDA path because I didn't find CUDA folder under /usr/local/, but I don't have root access because it's the server of university so it seems cannot install CUDA by myself.

Do you have any idea in this case? 
Thanks.

**Comment by rusty1s** [comment]
You can check the CUDA path by running `which nvcc`.

**Comment by zhiqiangzhongddu** [comment]
Thanks for your reply.

I got the CUDA path as:
>>which nvcc:
/opt/apps/resif/data/production/v1.1-20180716/default/software/system/CUDA/10.0.130/bin/nvcc
and 
>>pip install torch-scatter
Requirement already satisfied: torch-scatter in ./anaconda3/lib/python3.7/site-packages (1.3.0)
>>pip install torch-geometric
Requirement already satisfied: torch-geometric in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (1.3.0)
Requirement already satisfied: numpy in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from torch-geometric) (1.16.2)
Requirement already satisfied: networkx in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from torch-geometric) (2.2)
Requirement already satisfied: h5py in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from torch-geometric) (2.9.0)
Requirement already satisfied: plyfile in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from torch-geometric) (0.7)
Requirement already satisfied: rdflib in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from torch-geometric) (4.2.2)
Requirement already satisfied: scipy in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from torch-geometric) (1.2.1)
Requirement already satisfied: scikit-learn in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from torch-geometric) (0.20.3)
Requirement already satisfied: pandas in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from torch-geometric) (0.24.2)
Requirement already satisfied: decorator>=4.3.0 in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from networkx->torch-geometric) (4.4.0)
Requirement already satisfied: six in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from h5py->torch-geometric) (1.12.0)
Requirement already satisfied: pyparsing in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from rdflib->torch-geometric) (2.3.1)
Requirement already satisfied: isodate in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from rdflib->torch-geometric) (0.6.0)
Requirement already satisfied: python-dateutil>=2.5.0 in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from pandas->torch-geometric) (2.8.0)
Requirement already satisfied: pytz>=2011k in /mnt/irisgpfs/users/zzhong/anaconda3/lib/python3.7/site-packages (from pandas->torch-geometric) (2018.9)

and I also added "export PATH=/opt/apps/resif/data/production/v1.1-20180716/default/software/system/CUDA/10.0.130/bin${PATH:+:${PATH}}" into .bashrc, but still have the same error "ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'".

**Comment by zhiqiangzhongddu** [comment]
Furthermore, for the test of pytorch_scatter,
if I do like "python setup.py test" the no error,
>>  200 passed, 1 skipped in 3.98 seconds
But if I do test in the upper-level folder like "python pytorch_scatter/setup.py test", then there are some errors:
>> building 'torch_scatter.scatter_cpu' extension
gcc -pthread -B /home/users/zzhong/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/users/zzhong/.local/lib/python3.7/site-packages/torch/include -I/home/users/zzhong/.local/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/users/zzhong/.local/lib/python3.7/site-packages/torch/include/TH -I/home/users/zzhong/.local/lib/python3.7/site-packages/torch/include/THC -I/home/users/zzhong/anaconda3/include/python3.7m -c cpu/scatter.cpp -o build/temp.linux-x86_64-3.7/cpu/scatter.o -Wno-unused-variable -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=scatter_cpu -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++11
gcc: error: cpu/scatter.cpp: No such file or directory
error: command 'gcc' failed with exit status 1.

**Comment by zhiqiangzhongddu** [comment]
I tried to exported those paths, still doesn't work.


export PATH=/opt/apps/resif/data/production/v1.1-20180716/default/software/system/CUDA/10.0.130/bin:$PATH

export CPATH=/opt/apps/resif/data/production/v1.1-20180716/default/software/system/CUDA/10.0.130/include:$CPATH

export LD_LIBRARY_PATH=/opt/apps/resif/data/production/v1.1-20180716/default/software/system/CUDA/10.0.130/lib64:$LD_LIBRARY_PATH

**Comment by rusty1s** [comment]
I believe calling python setup.py only works in the root folder, so that error is to be expected. You should stop worry about CUDA path issues since installation does actually work. I guess the PyG examples just run fine? Like gat.py or pointnet2_classification.py?

**Comment by zhiqiangzhongddu** [comment]
None of the PyG examples works, here is the output of pointnet2_classification.py:

Traceback (most recent call last):
  File "pointnet2_classification.py", line 6, in <module>
    from torch_geometric.datasets import ModelNet
  File "/home/users/zzhong/anaconda3/lib/python3.7/site-packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.nn
  File "/home/users/zzhong/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/__init__.py", line 2, in <module>
    from .data_parallel import DataParallel
  File "/home/users/zzhong/anaconda3/lib/python3.7/site-packages/torch_geometric/nn/data_parallel.py", line 5, in <module>
    from torch_geometric.data import Batch
  File "/home/users/zzhong/anaconda3/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/users/zzhong/anaconda3/lib/python3.7/site-packages/torch_geometric/data/data.py", line 7, in <module>
    from torch_sparse import coalesce
  File "/home/users/zzhong/anaconda3/lib/python3.7/site-packages/torch_sparse/__init__.py", line 2, in <module>
    from .coalesce import coalesce
  File "/home/users/zzhong/anaconda3/lib/python3.7/site-packages/torch_sparse/coalesce.py", line 2, in <module>
    import torch_scatter
  File "/home/users/zzhong/anaconda3/lib/python3.7/site-packages/torch_scatter/__init__.py", line 3, in <module>
    from .mul import scatter_mul
  File "/home/users/zzhong/anaconda3/lib/python3.7/site-packages/torch_scatter/mul.py", line 3, in <module>
    from torch_scatter.utils.ext import get_func
  File "/home/users/zzhong/anaconda3/lib/python3.7/site-packages/torch_scatter/utils/ext.py", line 5, in <module>
    import torch_scatter.scatter_cuda
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'

**Comment by rusty1s** [comment]
Ah, I guess you may have multiple `torch-scatter` versions installed. Python takes the first one, for which an installation error may have occurred. Please run:
```
pip uninstall torch-scatter
```
multiple times as long as you are sure there are no `torch-scatter` packages left. Then reinstall `torch-scatter` and try again.

**Comment by zhiqiangzhongddu** [comment]
Yes, you are right. I uninstalled all related packages and re-install them by pip, now test examples of Py_G work fluent. Thanks a lot.

**Comment by rusty1s** [comment]
Wow, finally :) Glad that it is now working. Happy hacking :)
