### ISSUE TITLE
cuda runtime error (59)

### ISSUE THREAD

**Issue by yt2639** [rusty1s/pytorch_geometric#485]
python: 3.6
pytorch:1.1.0
CUDA: 10.0.130
torch-geometric-1.3.0
torch-scatter-1.3.0

Hi @rusty1s ! I am using NNConv, TopKPooling, and global_max_pool to construct my net. When training, there is some cuda error and traceback shows there is perhaps problem with torch_scatter/max.py. And after this error, if I run the training codes again, even `model=myGNN()` goes wrong. Could this be torch-scatter-1.3.0 problem?

But it's weird because if I run the training code not in for loop but one by one, it goes fine. Could you please give me some clues on where the codes went wrong? Many thanks!

```
o_feat=32
neuralnet1=nn.Sequential(nn.Linear(1, o_feat),
                         nn.BatchNorm1d(o_feat),
                         nn.ReLU(inplace=True),
                         nn.Linear(o_feat, 1*32)).to(device)
.... .... (neuralnet2, and neuralnet3 are very similar)

class myGNN(torch.nn.Module):
    def __init__(self):
        super(myGNN, self).__init__()
        
        self.conv1 = NNConv(in_channels=1, out_channels=32, nn=neuralnet1)
        self.pool1 = TopKPooling(32,0.8)
        
        self.conv2 = NNConv(in_channels=32, out_channels=64, nn=neuralnet2)
        self.pool2 = TopKPooling(64,0.8)
        
        self.conv3 = NNConv(in_channels=64, out_channels=128, nn=neuralnet3)
        self.pool3 = TopKPooling(128,0.8)
        
        self.lin1 = torch.nn.Linear(128,64)
        self.bn1 = torch.nn.BatchNorm1d(64)
        self.lin2 = torch.nn.Linear(64,32)
        self.bn2 = torch.nn.BatchNorm1d(32)
        self.lin3 = torch.nn.Linear(32,1)


    def forward(self, data):
        x,edge_index,edge_attr,batch=data.x.to(device),data.edge_index.to(device),data.edge_attr.to(device),data.batch.to(device)
        
        x = nn.ReLU(inplace=True)(self.conv1(x=x, edge_index=edge_index, edge_attr=edge_attr))
        x, edge_index,edge_attr,batch,_=self.pool1(x=x,edge_index=edge_index,edge_attr=edge_attr,batch=batch)

        x = nn.ReLU(inplace=True)(self.conv2(x=x, edge_index=edge_index, edge_attr=edge_attr))
        x, edge_index,edge_attr,batch,_=self.pool2(x=x,edge_index=edge_index,edge_attr=edge_attr,batch=batch)
        
        x = nn.ReLU(inplace=True)(self.conv3(x=x, edge_index=edge_index, edge_attr=edge_attr))
        x,_,_,batch,_=self.pool3(x=x,edge_index=edge_index,edge_attr=edge_attr,batch=batch)

        x = global_max_pool(x,batch)

        x = nn.ReLU(inplace=True)(self.bn1(self.lin1(x)))
        x = nn.ReLU(inplace=True)(self.bn2(self.lin2(x)))
        x = self.lin3(x)

        return x
```

Training code looks like:
```
model=myGNN()
model=model.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.003) # , weight_decay=5e-3
loss_func = nn.MSELoss()

for epoch in range(2):
    for dat in train_loader:
        #############
        model.train()
        #############
        optimizer.zero_grad()
        loss = loss_func(torch.squeeze(model(dat)), dat.y.to(device)) # input, target
        loss.backward()
        optimizer.step()
```

The traceback looks like:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-969960b6f804> in <module>
     19 
     20         loss = loss_func(torch.squeeze(model(dat)), dat.y.to(device)) # input, target
---> 21         loss.backward()
     22         optimizer.step()
     23 

/opt/conda/lib/python3.6/site-packages/torch/tensor.py in backward(self, gradient, retain_graph, create_graph)
    105                 products. Defaults to ``False``.
    106         """
--> 107         torch.autograd.backward(self, gradient, retain_graph, create_graph)
    108 
    109     def register_hook(self, hook):

/opt/conda/lib/python3.6/site-packages/torch/autograd/__init__.py in backward(tensors, grad_tensors, retain_graph, create_graph, grad_variables)
     91     Variable._execution_engine.run_backward(
     92         tensors, grad_tensors, retain_graph, create_graph,
---> 93         allow_unreachable=True)  # allow_unreachable flag
     94 
     95 

/opt/conda/lib/python3.6/site-packages/torch/autograd/function.py in apply(self, *args)
     75 
     76     def apply(self, *args):
---> 77         return self._forward_cls.backward(self, *args)
     78 
     79 

/opt/conda/lib/python3.6/site-packages/torch_scatter/max.py in backward(ctx, grad_out, grad_arg)
     26         if ctx.needs_input_grad[1]:
     27             grad_src = grad_out.new_zeros(index.size())
---> 28             grad_src.scatter_(ctx.dim, arg.detach(), grad_out)
     29 
     30         return None, grad_src, None, None

RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/generic/THCTensorScatterGather.cu:194
```

**Comment by rusty1s** [comment]
Hi, can you run the code with `CUDA_LAUNCH_BLOCKING=1 python ...` to check where exactly the error occurs?

**Comment by yt2639** [comment]
Hi, I actually used Jupyter Notebook and I also have set `os.environ['CUDA_LAUNCH_BLOCKING'] = '1'`.

**Comment by rusty1s** [comment]
Does this work when you replace the `global_max_pool` call with `global_mean_pool`?

**Comment by rusty1s** [comment]
Fixed in `torch-scatter=1.3.1`. Sorry for the inconvenience!

**Comment by yt2639** [comment]
Great, it's working now with `torch-scatter=1.3.1`! No worries, thank you for providing this amazing tool! 😉

**Comment by yt2639** [comment]
Sorry, I have another question about using PyG to do regression. Actually these codes above are used to do age prediction. I understand that I can divide the age into several ranges so that it becomes multi-class classification problem. But can we do THE **regression**? 

My `lin3 (torch.nn.Linear(32,1))` returns to 1 dimension and I found age should be positive so I returned `nn.Relu(inplace=True)(self.lin3(x))` in the forward function. Is this the proper way to do the age prediction? Many thanks!! 😉

**Comment by rusty1s** [comment]
You can omit the relu and just train against your targets with mse loss.

**Comment by yt2639** [comment]
Thank you!! I've tried that but the output of the model will be the same number. Specifically, for example, I have training data with batch size of 16. 
```
out=model(dat)
```
Then initially the prediction are not all the same but `MSE=2000` and after training for 30 epochs, although `MSE=400`, the output is all the same.
```
out=tensor[1.325,1.325,1.325,1.325,...,1.325,1.325,1.325]
```
Should I change `TopKPooling` into `Set2Set` as the QM9 example shows? The reason I am using `NNConv` is that I looked up the source code and assumed `NNConv` will make use of edge_attr. But `TopKPooling` does not seem like using edge_attr. I am super super confused... like which conv op, pooling op should I use, and is the model's bad performance due to low batch size..

**Comment by rusty1s** [comment]
Well, I can not really say why your network always produces the same output. This seems kinda strange, given that you have different initial node features and different edge connectivity for each example. You should verify why this is the case. Therefore, I suggest starting with a more simple baseline, *e.g.* a few layers of `NNConv` followed by `global_mean_pool` or `global_max_pool`.

`NNConv` is a good choice when having edge attributes. It will aggregate node features dependent on the given edge features. Although `TopKPooling` only considers nodes (to filter them), edge information can also flow into node features (given that you use `NNConv`).

I do not think the batch size should effect performance that much.
