### ISSUE TITLE
RuntimeError: copy_if failed to synchronize: device-side assert triggered

### ISSUE THREAD

**Issue by zhenhuascut** [rusty1s/pytorch_geometric#803]
## 🐛 Bug

When I use the GCNConv in my codes, it happens.

batch_x
Out[6]: Batch(batch=[4368], edge_index=[2, 7456], x=[4368, 1])

batch_x_temp = self.embeddings(batch_x.x).squeeze()
batch_x_temp.shape
Out[9]: torch.Size([4368, 100])

self.gcn1(batch_x_temp, batch_x.edge_index)
RuntimeError: CUDA error: device-side assert triggered

the problem happens in norm in GCNConv

row, col = edge_index
row
Out[9]: tensor([18621, 18645, 18645,  ...,  4365,  4366,  4367], device='cuda:0')
col
Out[10]: tensor([18645,   903, 18621,  ...,  4365,  4366,  4367], device='cuda:0')

deg = scatter_add(edge_weight, row, dim=0, dim_size=num_nodes)

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653099582/work/aten/src/THC/THCCachingHostAllocator.cpp line=265 error=59 : device-side assert triggered

Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-4d8c1acffbe6>", line 1, in <module>
    F.relu(self.gcn1(batch_x_temp, batch_x.edge_index))
  File "/root/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 95, in forward
    self.improved, x.dtype)
  File "/root/anaconda3/lib/python3.6/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 85, in norm
    deg_inv_sqrt[deg_inv_sqrt == float('inf')] = 0
RuntimeError: copy_if failed to synchronize: device-side assert triggered

## Environment

* OS:
* Python version:
* PyTorch version:
* CUDA/cuDNN version:
* GCC version:
* Any other relevant information:

**Comment by rusty1s** [comment]
Seems to be related to https://github.com/rusty1s/pytorch_geometric/issues/669.

**Comment by zhenhuascut** [comment]
Yep, I found the reason. It is related to edge_mat.

**Comment by XiaonanHuang** [comment]
Hi!
I also meet the same problem of GATConv in my code, how dou you solve it? why it is related to edge_mat? @zhenhuascut 
Thank you very much!
