### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by NIRVANALAN** [rusty1s/pytorch_geometric#863]
## ❓ Questions & Help: 
when i run
```
python geniepath.py
```

![image](https://user-images.githubusercontent.com/23359323/70968080-35bd2d00-20d3-11ea-9d2f-0667035b70d7.png)
package version failure or?

**Comment by rusty1s** [comment]
Mh, I cannot reproduce this error. Do the other examples work for you, *e.g.*, `gat.py`?

**Comment by NIRVANALAN** [comment]
Seems it's because of my PyG version does not match my nvidia-driver CUDA version, sorry for that.
PyG does not support Cuda 10.2?

**Comment by NIRVANALAN** [comment]
emm I still cannot solve this problem, and when I run any model in example.py, I encounter this problem
![image](https://user-images.githubusercontent.com/23359323/71409458-a1c40600-267c-11ea-99b7-1d110dc7130e.png)
what should I do?

**Comment by rusty1s** [comment]
Can you check if the tests in `torch-scatter` pass?

**Comment by NIRVANALAN** [comment]
![image](https://user-images.githubusercontent.com/23359323/71409613-39295900-267d-11ea-9e4c-f05f1fcbd62a.png)
the test says it has 2 failures
![image](https://user-images.githubusercontent.com/23359323/71409632-4a726580-267d-11ea-8a47-60616ef0aa5f.png)

**Comment by rusty1s** [comment]
These are the tests of `torch-geometric`, aren't they?

**Comment by NIRVANALAN** [comment]
yes, which scipt should I run?

**Comment by rusty1s** [comment]
`python setup.py test` in the `torch-scatter` repository.

**Comment by NIRVANALAN** [comment]
![image](https://user-images.githubusercontent.com/23359323/71409935-3da24180-267e-11ea-83b2-16ce525afd0c.png)
many tests have failed..

**Comment by NIRVANALAN** [comment]
something to do with cuda version ? I am using P100 with 16GB mem

**Comment by rusty1s** [comment]
What does the installation of `torch-scatter` say? Especially the `nvcc` call?

**Comment by NIRVANALAN** [comment]
do you mean the log from ```python setup.py install ``` of ```torch-scatter``` ? i did not find nvcc call

**Comment by rusty1s** [comment]
Yeah, there must be one for sure :)
Eventually you need to force re-compiling via:
```
rm -rf build/ && python setup.py install
```

**Comment by NIRVANALAN** [comment]
thanks for your advice, I reinstalled my torch and other dependencies, and now the error became..
![image](https://user-images.githubusercontent.com/23359323/71412056-d341cf00-2686-11ea-8e73-f356d9a7af92.png)
actually i have encounted this before, and I am using cuda10.0

**Comment by NIRVANALAN** [comment]
does that mean the kernel is not inplemented in this version of torch(1.1.0)?

**Comment by rusty1s** [comment]
This is weird, and not related to `torch-scatter`.
```python
import torch
torch.tensor([True, False, True]).sum()
```
works for me (PyTorch 1.3.0).

**Comment by NIRVANALAN** [comment]
![image](https://user-images.githubusercontent.com/23359323/71412325-35e79a80-2688-11ea-97e8-57d3d702b79f.png)
it's mask.sum() that fails

**Comment by rusty1s** [comment]
It seems that you need `torch>=1.2.0`. Alternatively, just re-write it to
```python
data.y[mask].long().sum()
```

**Comment by NIRVANALAN** [comment]
thanks a lot, you are such a reliable man ;)
the dependency reqirements of PyG is really strict, but marvelous work
thanks for your contribution again!

**Comment by NIRVANALAN** [comment]
also, seems that if i have reinstalled torch, i need to reinstall torch-scatter, torch-cluster again?

**Comment by rusty1s** [comment]
Thank you! Glad that it is now working. It sadly quite hard to keep backwards compatibility with PyTorch. And yes, re-installing torch requires re-installing of the packages :(

**Comment by NIRVANALAN** [comment]
got it, thanks;
your hard work contributes greately to our research..hope there will be a better way of keeping compatibility of dependencies which can relieve your stress..
